#! /usr/bin/bash

update_configs_files() {
    rm -rf "$DEV_ENV/env/.config"
    mkdir -p "$DEV_ENV/env/.config"
    for config in "$@"; do
        echo -e "\t $config"
        cp -r "$HOME/.config/$config" "$DEV_ENV/env/.config"
    done
}

# config files to keep track of in the repo
confs=(
    awesome
    dunst
    fastfetch
    ghostty
    hyfetch.json
    hypr
    kickoff
    kitty
    nvim
    ranger
    rofi
    waybar
)
echo "Updating configs files"
update_configs_files "${confs[@]}"

update_env_files() {
    for env_file in "$@"; do
        echo -e "\t $env_file"
        cp -r "$HOME/$env_file" "$DEV_ENV/env/"
    done
}

echo "Copying envs files"
envs=(
    ".bash_aliases"
    ".bashrc"
    ".zshrc"
    ".tmux.conf"
)
update_env_files "${envs[@]}"



# update the git repo
{
    cd $DEV_ENV

    if [[ "$(git status)" == *"nothing to commit, working tree clean"* ]]; then
      echo "Nothing to commit. Exiting."
      exit 0
    fi

    read -p "continue? [y/N] " confirm
    if [[ "$confirm" =~ ^[Yy]$ ]]; then
      git add .
      git commit -m "chore: automated commit"
      git push
    fi
}
