#! /usr/bin/bash

update_configs_files() {
    rm -rf "$DEV_ENV/env/.config"
    mkdir -p "$DEV_ENV/env/.config"
    for config in "$@"; do
        echo -e "\t\t$config"
        cp -r "$HOME/.config/$config" "$DEV_ENV/env/.config"
    done
}
update_env_files() {
    for env_file in "$@"; do
        echo -e "\t\t$env_file"
        cp -r "$HOME/$env_file" "$DEV_ENV/env/"
    done
}

# config files to keep track of in the repo
confs=(
    awesome
    dunst
    fastfetch
    fcitx
    fcitx5
    ghostty
    hyfetch.json
    hypr
    kickoff
    kitty
    nvim
    ranger
    rofi
    waybar
)

envs=(
    ".bash_aliases"
    ".bashrc"
    ".zshrc"
    ".tmux.conf"
)

echo "Updating configs files"
update_configs_files "${confs[@]}"

echo "Copying envs files"
update_env_files "${envs[@]}"

# update the git repo
{
    cd $DEV_ENV

    git -C "$DEV_ENV" -c color.status=always status

    # Use plain text (no colors) to check for "nothing to commit"
    status=$(git -C "$DEV_ENV" status --porcelain)

    if [[ -z "$status" ]]; then
        exit 0
    fi

    read -p "continue? [y/N] " confirm
    if [[ "$confirm" =~ ^[Yy]$ ]]; then
      git add .
      git commit -m "chore: automated commit"
      git push
    fi
}
