#! /usr/bin/bash

sudo pacman -Syu --needed --noconfirm \
    discord \
    firefox \
    go \
    hyprland \
    hyprpaper \
    jre-openjdk \
    kitty \
    lua \
    npm \
    nvim \
    rofi-wayland \
    steam \
    steam-native-runtime \
    thunderbird \
    tmux \
    waybar \
    wl-clipboard

yay -S --needed --noconfirm \
    brave-bin \
    proton-ge-custom-bin \
    spotify \
