#! /usr/bin/bash

sudo pacman -Syu --needed --noconfirm \
    bat \
    discord \
    dotnet-runtime \
    dotnet-sdk \
    fastfetch \
    fcitx5-configtool \
    fcitx5-gtk \
    fcitx5-mozc \
    firefox \
    gimp \
    go \
    htop \
    hyprland \
    hyprpaper \
    jre-openjdk \
    kitty \
    lib32-nvidia-utils \
    libva-nvidia-driver \
    love \
    lua \
    npm \
    nvidia-utils \
    nvim \
    nvtop \
    python-pillow \
    qbittorrent \
    ranger \
    ripgrep \
    rofi-wayland \
    rustup \
    spotify-launcher \
    steam \
    steam-native-runtime \
    thunderbird \
    tmux \
    torbrowser-launcher \
    ttf-fira-code \
    waybar \
    wev \
    wl-clipboard \
    wtype \


yay -S --needed --noconfirm \
    brave-bin \
    keyd \
    ckb-next \
    vencord \
    visual-studio-code-bin \
    minecraft-launcher \
    proton-ge-custom-bin \
    swhkd-bin \
