#! /usr/bin/bash

sudo pacman -Syu --needed --noconfirm \
    kitty \
    waybar rofi-wayland hyprland hyprpaper \
    discord firefox \
    nvim go lua tmux

yay -S brave-bin \
    --needed --noconfirm
