#! /usr/bin/bash

yay -S --needed --noconfirm \
    brave-bin \
    swhkd \
    chatterino2-git \
    ckb-next-git \
    hyprshot \
    keyd \
    minecraft-launcher \
    proton-ge-custom-bin \
    rider \
    unityhub \
    visual-studio-code-bin \
    wlrobs-hg \
    wshowkeys-mao-git \
    zen-browser-bin \
