#! /usr/bin/bash

aur=(
    ckb-next-git
    cnijfilter2 # driver for Canon printers
    cursor-bin
    fcitx5-mozc-ut # Better dictionaries for Mozc
    minecraft-launcher
    mpvpaper
    pandoc
    protontricks
    r2modman-bin # Thunderstore client
    timg # display images in terminal
    unityhub
    vencord-bin
    vesktop
    visual-studio-code-bin
    wlrobs # OBS plugin for screen capture on wayland
    zen-browser-bin
)

langs=(
    clang
    clojure
    aspnet-runtime
    dotnet-runtime
    dotnet-sdk
    elixir
    erlang
    go
    zig
    zls
    gopls
    jdk-openjdk
    maven
    leiningen # stack-like thing for clojure
    love
    lua
    npm
    rustup
    texlive-basic
    texlive-bibtexextra
    texlive-binextra
    texlive-fontsrecommended
    texlive-lang
    texlive-latex
    texlive-latexextra
    texlive-latexrecommended
    texlive-luatex
    texlive-mathscience
    texlive-plaingeneric
    texlive-xetex
    typst
    yarn
)

ides=(
    intellij-idea-community-edition
)

term_tools=(
    chafa
    bat
    btop
    bc
    eza
    fastfetch
    fzf
    ghostty
    github-cli
    htop
    ncdu # check disk info (kinda like WinDirStat)
    hyfetch
    kitty
    nvim
    nvtop
    micro
    ripgrep
    tmux
    tree
    yazi
    zsh
    emacs
)

ime=(
    fcitx5-configtool
    fcitx5-gtk
    fcitx5-hangul
    fcitx5-rime
    # fcitx5-mozc # use fcitx5-mozc-ut from AUR instead
)

system=(
    brightnessctl
    glfw
    mercurial # require to install wlrobs-hg
    gnome-keyring
    seahorse # gui to manage gnome-keyring
    keyd
    pavucontrol
    keepassxc
    qt5-wayland
    xdg-desktop-portal-hyprland
)

wm=(
    cliphist
    dunst
    grim
    hypridle
    hyprland
    hyprlock
    hyprpaper
    hyprpicker
    hyprshot
    pcmanfm
    rofi-emoji
    rofi-wayland
    swww
    tesseract
    tesseract-data-chi_sim
    tesseract-data-eng
    tesseract-data-jpn
    waybar
    wl-clipboard
    wlsunset
)

browser=(
    firefox
    thunderbird
    torbrowser-launcher
)

extra=(
    discord
    geogebra
    gimp
    libreoffice-still
    lutris
    obsidian
    obs-studio
    okular
    prismlauncher
    qbittorrent
    spotify-launcher
    steam
    steam-native-runtime
    wev
    wine
    wine-mono
)

fonts=(
    noto-fonts-cjk
    ttf-fira-code
    ttf-nerd-fonts-symbols-mono
)

packages=(
    "${aur[@]}"
    "${browser[@]}"
    "${codes[@]}"
    "${extra[@]}"
    "${fonts[@]}"
    "${ides[@]}"
    "${ime[@]}"
    "${langs[@]}"
    "${system[@]}"
    "${term_tools[@]}"
    "${wm[@]}"
)


echo "Updating repos..."
yay

echo "Checking packages..."
yay -S --needed "${packages[@]}"
