#! /usr/bin/bash

aur=(
    ckb-next-git
    cursor-bin
    fcitx5-mozc-ut
    minecraft-launcher
    mpvpaper
    pandoc
    r2modman-bin
    timg # display images in terminal
    unityhub
    vencord-bin
    vesktop
    visual-studio-code-bin
    wlrobs-hg # OBS plugin for screen capture on wayland
    zen-browser-bin
)

langs=(
    clang
    clojure
    dotnet-runtime
    dotnet-sdk
    elixir
    erlang
    go
    gopls
    jdk-openjdk
    leiningen
    love
    lua
    npm
    python-praw
    r
    rustup
    texlive-basic
    texlive-bibtexextra
    texlive-binextra
    texlive-fontsrecommended
    texlive-lang
    texlive-latex
    texlive-latexextra
    texlive-latexrecommended
    texlive-luatex
    texlive-mathscience
    texlive-plaingeneric
    texlive-xetex
    typst
    yarn
)

term_tools=(
    bat
    btop
    eza
    fastfetch
    fzf
    ghostty
    github-cli
    htop
    hyfetch
    kitty
    nvim
    nvtop
    ripgrep
    tmux
    tree
    yazi
    zsh
    emacs

)

ime=(
    fcitx5-configtool
    fcitx5-gtk
    fcitx5-hangul
    fcitx5-rime
    # fcitx5-mozc # use fcitx5-mozc-ut from AUR instead
)

system=(
    brightnessctl
    glfw
    gnome-keyring
    keyd
    pavucontrol
)
wm=(
    cliphist
    dunst
    hypridle
    hyprland
    hyprlock
    hyprpaper
    hyprpicker
    hyprshot
    rofi-emoji
    rofi-wayland
    swww
    tesseract
    tesseract-data-eng
    waybar
    wl-clipboard
    wlsunset
)
browser=(
    firefox
    thunderbird
    torbrowser-launcher
)
extra=(
    discord
    geogebra
    gimp
    libreoffice-still
    obsidian
    obs-studio
    okular
    qbittorrent
    spotify-launcher
    steam
    steam-native-runtime
    wev
    zed
)
fonts=(
    noto-fonts-cjk
    ttf-fira-code
    ttf-nerd-fonts-symbols-mono
)

packages=(
    "${browser[@]}"
    "${codes[@]}"
    "${extra[@]}"
    "${fonts[@]}"
    "${ime[@]}"
    "${langs[@]}"
    "${system[@]}"
    "${term_tools[@]}"
    "${wm[@]}"
)



if [[ " $* " == *" nopac "* ]]
then
    echo "skipping pacman..."
else
    echo "Checking official repos..."
    sudo pacman -Syu --needed "${packages[@]}"
fi

if [[ " $* " == *" aur "* ]]
then
    echo "Checking AUR..."
    yay -S --needed "${aur[@]}"
else
    echo "Skipping AUR..."
fi
