# notifications
exec-once = dunst

# input
exec-once = ckb-next
exec-once = fcitx5

# wallpapers
# exec-once = hyprpaper
# exec-once = wpaperd
exec-once = swww-daemon
# exec-once = mpvpaper -p -o "--panscan=1.0 vf-add=fps=10:round=near no-audio --loop-file=inf" ALL ~/personal/wallpapers/void-trace.webm

# bar
exec-once = waybar
# exec-once = hyprland-autoname-workspaces

# copy/paste
exec-once = wl-paste --watch cliphist store


# exec-once = wshowkeys -a top -a right -m 100 -F "fira-code-retina 14"


# exec-once = hyprsunset # crashes my graphics (nvidia moment 😿)
exec-once = wlsunset -T 6500 -t 5000




exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland

