exec-once = $notifications
exec-once = $bar
# exec-once = $email
exec-once = $browser
exec-once = ghostty
# exec-once = emacs --daemon
exec-once = fcitx5
exec-once = ckb-next
exec-once = swww-daemon
exec-once = blueman-applet
exec-once = wlsunset -T 6500 -t 5000
exec-once = $HOME/.local/bin/wellbeing server
exec-once = wl-paste --watch cliphist store
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=hyprland
