exec-once = dunst
exec-once = ckb-next
exec-once = fcitx5
# exec-once = hypridle
# exec-once = hyprpaper
exec-once = wpaperd
exec-once = waybar
exec-once = wl-paste --watch cliphist store
# exec-once = wshowkeys -a top -a right -m 100 -F "fira-code-retina 14"



# exec-once = hyprsunset # crashes my graphics (nvidia moment 😿)
exec-once = wlsunset -S 10:30 -s 21:30
