$bar = waybar
$browser = zen-browser
$email = thunderbird
$emoji = rofi -modi emoji -show emoji
$fileManager = dolphin
$menu = rofi -show drun # uses rofi-wayland
$notifications = dunst
$run_menu = rofi -show run
$showWindows = rofi -show
$terminal = ghostty

$mainMod = SUPER

$ws01 = 1
$ws02 = 2
$ws03 = 3
$ws04 = 4
$ws05 = 5
$ws06 = 6
$ws07 = 7
$ws08 = 8
$ws09 = 9
$ws10 = 10
