# browsers
windowrule = workspace $ws01, class:firefox
windowrule = workspace $ws01, class:zen
windowrule = workspace $ws02, class:kitty
windowrule = workspace $ws02, class:com.mitchellh.ghostty
windowrule = workspace $ws04, class:cs2
windowrule = workspace $ws04, class:steam_app_.*
windowrule = workspace $ws04, class:(?i).*minecraft.*
windowrule = workspace $ws07 silent, class:steam
windowrule = workspace $ws06, class:thunderbird
windowrule = workspace $ws08, class:Spotify
windowrule = workspace $ws09, class:discord
windowrule = workspace $ws09, class:vesktop


windowrulev2 = rounding 0, class:zen
windowrulev2 = bordersize 0, class:zen

windowrule = size 900 800, class:org.kde.dolphin
windowrule = float, class:org.kde.dolphin
windowrule = center, class:org.kde.dolphin

# windowrule = fullscreenstate 0 2, class:firefox
# windowrule = fullscreenstate 0 0, floating:1

# PIP
# windowrulev2 = float, title:.*Picture-in-Picture.*
# windowrulev2 = bordersize 0, title:.*Picture-in-Picture.*
windowrule = workspace $ws10 silent, title:.*Picture-in-Picture.*
windowrulev2 = fullscreen, title:.*Picture-in-Picture.*
windowrulev2 = pin, title:.*Picture-in-Picture.*
windowrulev2 = opacity override 1.0 override 1.0 override 1.0, title:.*Picture-in-Picture.*
windowrulev2 = opacity override 1.0 override 1.0 override 1.0, title:.*YouTube.*
windowrulev2 = opacity override 1.0 override 1.0 override 1.0, title:.*Twitch.*

# Ignore maximize requests from apps.
windowrulev2 = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0


# windowrule = float, class:.*


# wallpaper selector with kitty
windowrule = float, class:kitty_walls
windowrule = size 1600 900, class:kitty_walls
windowrule = center, class:kitty_walls
windowrule = pin, class:kitty_walls
