# browsers
windowrule = workspace $ws01, class:zen
windowrule = workspace $ws02, class:com.mitchellh.ghostty
windowrule = workspace $ws04, class:cs2
windowrule = workspace $ws04, class:steam_app_.*
windowrule = workspace $ws04, class:(?i).*minecraft.*
windowrule = workspace $ws05, class:steam
windowrule = workspace $ws06, class:vivaldi-stable
windowrule = workspace $ws07, class:thunderbird
windowrule = workspace $ws08, class:Spotify
windowrule = workspace $ws09, class:discord
windowrule = workspace $ws09, class:vesktop

windowrule = float, class: steam_app_1551360

windowrule = float, title: Save.*
windowrule = center, title: Save.*
windowrule = size 1000 700, title: Save.*

windowrule = size 900 700, class:Pcmanfm
windowrule = float, class:Pcmanfm
windowrule = center, class:Pcmanfm

windowrule = size 900 300, class:org.gnome.gedit
windowrule = float, class:org.gnome.gedit
windowrule = center, class:org.gnome.gedit

windowrule = opacity 0.8 override, tag: dragged

# PIP
windowrule = workspace $ws10 silent, title:.*Picture-in-Picture.*

windowrulev2 = opacity override 1.0 override 1.0 override 1.0, title:.*Picture-in-Picture.*
windowrulev2 = opacity override 1.0 override 1.0 override 1.0, title:.*YouTube.*
windowrulev2 = opacity override 1.0 override 1.0 override 1.0, title:.*Twitch.*

# Ignore maximize requests from apps.
windowrulev2 = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
