# browsers
windowrule = workspace $ws01, class:firefox
windowrule = workspace $ws01, class:zen

# windowrulev2 = rounding 0, class:firefox
windowrulev2 = rounding 0, class:zen
windowrulev2 = bordersize 0, class:zen

# windowrule = fullscreenstate 0 2, class:firefox
# windowrule = fullscreenstate 0 0, floating:1

# games
windowrule = workspace $ws07, class:steam_app_2357570
windowrule = workspace $ws07, class:steam
windowrule = workspace $ws07, class:.*Minecraft.*

# lesser used apps
# windowrule = workspace $ws08, class:thunderbird
windowrule = workspace $ws08, class:Spotify
windowrule = workspace $ws09, class:discord
windowrule = workspace $ws09, class:vesktop


# PIP
# windowrulev2 = float, title:.*Picture-in-Picture.*
# windowrulev2 = bordersize 0, title:.*Picture-in-Picture.*
windowrule = workspace $ws10 silent, title:.*Picture-in-Picture.*
windowrulev2 = pin, title:.*Picture-in-Picture.*
windowrulev2 = opacity override 1.0 override 1.0 override 1.0, title:.*Picture-in-Picture.*
windowrulev2 = opacity override 1.0 override 1.0 override 1.0, title:.*YouTube.*
windowrulev2 = opacity override 1.0 override 1.0 override 1.0, title:.*Twitch.*

# Ignore maximize requests from apps.
windowrulev2 = suppressevent maximize, class:.*
# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
