workspace = $ws01, monitor:HDMI-A-1, default:true
workspace = $ws02, monitor:HDMI-A-1
workspace = $ws03, monitor:HDMI-A-1
workspace = $ws04, monitor:HDMI-A-1
workspace = $ws05, monitor:HDMI-A-1
workspace = $ws06, monitor:HDMI-A-1
workspace = $ws07, monitor:HDMI-A-1
workspace = $ws08, monitor:HDMI-A-1
workspace = $ws09, monitor:HDMI-A-1
workspace = $ws10, monitor:eDP-1, default:true

