workspace = $ws01, defaultName:brws, monitor:HDMI-A-1, default:true
workspace = $ws02, defaultName:code, monitor:HDMI-A-1
workspace = $ws03, defaultName:misc, monitor:HDMI-A-1
workspace = $ws04, defaultName:misc, monitor:HDMI-A-1
workspace = $ws05, defaultName:misc, monitor:HDMI-A-1
workspace = $ws06, defaultName:misc, monitor:HDMI-A-1
workspace = $ws07, defaultName:game, monitor:HDMI-A-1
workspace = $ws08, defaultName:maso, monitor:HDMI-A-1
workspace = $ws09, defaultName:disc, monitor:HDMI-A-1
workspace = $ws10, defaultName:xtra, monitor:eDP-1, default:true

