workspace = $ws01, defaultName:browser, monitor:HDMI-A-1, default:true
workspace = $ws02, defaultName:2, monitor:HDMI-A-1
workspace = $ws03, defaultName:3, monitor:HDMI-A-1
workspace = $ws04, defaultName:4, monitor:HDMI-A-1
workspace = $ws05, defaultName:5, monitor:HDMI-A-1
workspace = $ws06, defaultName:6, monitor:HDMI-A-1
workspace = $ws07, defaultName:gayming, monitor:HDMI-A-1
workspace = $ws08, defaultName:spotify, monitor:HDMI-A-1
workspace = $ws09, defaultName:discord, monitor:HDMI-A-1
workspace = $ws10, defaultName:_, monitor:eDP-1, default:true

# no gaps when only one window is active
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]
windowrule = bordersize 0, floating:0, onworkspace:f[1]
windowrule = rounding 0, floating:0, onworkspace:f[1]
