#! /usr/bin/bash

aur=(
	ani-cli
	brave-bin
	ckb-next-git
	kickoff
	minecraft-launcher
	mpvpaper
	timg
	unityhub
	vencord-bin
	vesktop
	visual-studio-code-bin
	wlrobs-hg
	zen-browser-bin
)

packages=(
	bat
	brightnessctl
	btop
	cliphist
	discord
	dotnet-runtime
	dotnet-sdk
	dunst
	eza
	fastfetch
	fcitx5-configtool
	fcitx5-gtk
	fcitx5-mozc
	firefox
	fish
	fzf
	geogebra
	gimp
	github-cli
	glfw
	gnome-keyring
	go
	gopls
	htop
	hyfetch
	hypridle
	hyprland
	hyprlock
	hyprpaper
	hyprpicker
	hyprshot
	jre-openjdk
	keyd
	kitty
	libreoffice-still
	love
	lua
	noto-fonts-cjk
	npm
	nvim
	nvtop
	obsidian
	okular
	pavucontrol
	qbittorrent
	ripgrep
	rofi-emoji
	rofi-wayland
	rustup
	spotify-launcher
	steam
	steam-native-runtime
	swww
	tesseract
	tesseract-data-eng
	thunderbird
	tmux
	torbrowser-launcher
	tree
	ttf-fira-code
	ttf-nerd-fonts-symbols-mono
	typst
	waybar
	wev
	wl-clipboard
	wlsunset
	wtype
	yarn
	yazi
	zsh
)

sudo pacman -Syu --needed "${packages[@]}"

if [ -n "$1" ]
then
	echo "Checking AUR..."
	yay -S --needed "${aur[@]}"
fi
