#!/usr/bin/bash

pkgs=(
	texlive-basic
	texlive-bibtexextra
	texlive-binextra
	texlive-fontsrecommended
	texlive-lang
	texlive-latex
	texlive-latexextra
	texlive-latexrecommended
	texlive-luatex
	texlive-mathscience
	texlive-plaingeneric
	texlive-xetex
)

sudo pacman -Syu --needed "${pkgs[@]}"
