#! /usr/bin/bash

yay -S --needed \
    ani-cli \
    brave-bin \
    chatterino2-git \
    ckb-next-git \
    eww \
    hyprland-autoname-workspaces-git \
    hyprshot \
    minecraft-launcher \
    mpvpaper \
    proton-ge-custom-bin \
    seer-gdb \
    sherlock-launcher-bin \
    sleek-bin \
    spotdl \
    swhkd \
    timg \
    unityhub \
    vencord-bin \
    visual-studio-code-bin \
    waytrogen \
    wlrobs-hg \
    wshowkeys-mao-git \

# yay -S --needed --noconfirm   wttrbar
