#!/usr/bin/bash

echo "$1 -> path to drive"
echo "$2 -> path to zen profile"

if [ -n "$1" ] && [ -n "$2" ]; then
    {
        cd "$1"
        tar -cJvf personal.tar.xz ~/personal/
        tar -czvf minecraft.tar.gz ~/.minecraft
        tar -czvf zen-profile.tar.gz "$2"
    }
fi
