# $surtrLookingAway = /home/alice/personal/wallpapers/8616f28534cdc6705f829ee1fe6fff32.jpg
# $kanagawa = /home/alice/personal/wallpapers/kanagawa-waves.jpeg
# $greyMoon = /home/alice/personal/wallpapers/moon.png
# $grey-city-train-tracks = /home/alice/personal/wallpapers/grey-city-train-tracks.jpg
$storm = /home/alice/personal/wallpapers/storm.jpg
# $glazy = /home/alice/personal/wallpapers/glazy.png
# $bucket = /home/alice/personal/wallpapers/bucket.png
# $blaze = /home/alice/personal/wallpapers/drunk-blaze.png
# $catVibing = /home/alice/personal/wallpapers/cat-vibin.png
# $knifeGirl = /home/alice/personal/wallpapers/girl-bending-knife.jpg
# $sung = /home/alice/personal/wallpapers/sung\ jin\ woo\ chilling.jpg


preload = $storm
wallpaper = ,$storm
