listener {
    timeout = 60
    on-timeout = hyprlock
    on-resume = notify-send "Welcome back!"
}

listener {
    timeout = 120
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
