listener {
    timeout = 7200 # 2 hours
    on-timeout = hyprlock
    on-resume = notify-send "Welcome back!"
}

listener {
    timeout = 14400 # 4 hours
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
