# $surtrLookingAway = /home/alice/Pictures/8616f28534cdc6705f829ee1fe6fff32.jpg
$kanagawa = /home/alice/Pictures/kanagawa-waves.jpeg
# $greyMoon = /home/alice/Pictures/moon.png


preload = $kanagawa
wallpaper = ,$kanagawa

ipc = off
