# $surtrLookingAway = /home/alice/personal/dev-env/env/wallpapers/8616f28534cdc6705f829ee1fe6fff32.jpg
# $kanagawa = /home/alice/personal/dev-env/env/wallpapers/kanagawa-waves.jpeg
# $greyMoon = /home/alice/personal/dev-env/env/wallpapers/moon.png
# $grey-city-train-tracks = /home/alice/personal/dev-env/env/wallpapers/grey-city-train-tracks.jpg
# $storm = /home/alice/personal/dev-env/env/wallpapers/storm.jpg
# $glazy = /home/alice/personal/dev-env/env/wallpapers/glazy.png
$bucket = /home/alice/personal/dev-env/env/wallpapers/bucket.png
# $blaze = /home/alice/personal/dev-env/env/wallpapers/drunk-blaze.png
# $catVibing = /home/alice/personal/dev-env/env/wallpapers/cat-vibin.png


preload = $bucket
wallpaper = ,$bucket

ipc = off
