listener {
    timeout = 300
    on-timeout = hyprlock
    on-resume = notify-send "Welcome back!"
}

# maybe it will work this time... ?
listener {
    timeout = 120
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
