set-option -g default-shell /bin/zsh

set -g default-terminal "tmux-256color"
set -s escape-time 0

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style 'bg=#191724 fg=#31748F'
set -g base-index 1

set-window-option -g mode-keys vi

set-option -g status-left-length 40

# Example status-left to show session name

bind-key -r C-f run-shell "tmux neww ~/personal/dev-env/resources/scripts/tmux-sessionizer"
